/**
 * new_courses_catalog.ts — Task 5: 25 new course metadata rows.
 *
 * Single source of truth for the new-course catalog (ids, slugs, titles,
 * descriptions, categories, difficulties, durations, tags, prices). Content
 * (modules/topics/quizzes) lives in prisma/content/<slug>.ts and is attached by
 * reseed_new_courses.ts.
 *
 * PRICING RULE: Course.price must be the exact approved selling price below.
 * No originalPrice/MRP/discount/crossed-out pricing. Existing 9 courses keep ₹699.
 *
 * PUBLISHING RULE (§8): a course is created PUBLISHED only once its content file
 * exists and has sections; otherwise it stays unpublished (never shows a broken
 * public page). reseed_new_courses.ts enforces this.
 */

export interface NewCourseMeta {
  id: string;
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  shortDescription: string;
  categorySlug: string;
  price: number;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  duration: string;
  language: string;
  learningOutcomes: string[];
  prerequisites: string[];
  targetAudience: string[];
  tags: string[];
  certificateAvailable: boolean;
  featured: boolean;
}

export const ALL_CATEGORIES = [
  { slug: 'computer-office', name: 'Computer & Office', sortOrder: 1 },
  { slug: 'programming', name: 'Programming', sortOrder: 2 },
  { slug: 'web-development', name: 'Web Development', sortOrder: 3 },
  { slug: 'systems-technology', name: 'Systems & Technology', sortOrder: 4 },
  { slug: 'ai-future-skills', name: 'AI & Future Skills', sortOrder: 5 },
  { slug: 'iot', name: 'IoT', sortOrder: 6 },
  { slug: 'embedded-systems', name: 'Embedded Systems', sortOrder: 7 },
  { slug: 'electronics', name: 'Electronics', sortOrder: 8 },
  { slug: 'cad-design', name: 'CAD & Design', sortOrder: 9 },
  { slug: 'iti-trade-training', name: 'ITI & Trade Training', sortOrder: 10 },
];

export const NEW_COURSES: NewCourseMeta[] = [
  // ── Computer & Office ────────────────────────────────────────────────────
  {
    id: 'MSWord',
    slug: 'ms-word',
    title: 'MS Word — Professional Document Creation',
    shortTitle: 'MS Word',
    description:
      'Master Microsoft Word for real office work: professional letters, reports, resumes, mail-merge letters, tables, styles, track changes, and document formatting that is consistent and print-ready.',
    shortDescription: 'Professional documents, styles, mail merge, tables and track changes for real office work.',
    categorySlug: 'computer-office',
    price: 499,
    difficulty: 'Beginner',
    duration: '4 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Format professional letters, reports and resumes with styles and themes',
      'Build tables, headers/footers and page layouts that stay consistent',
      'Use mail merge to send personalized letters to many people at once',
      'Track, accept and reject changes when collaborating on a document',
      'Create reusable templates and automate repetitive work with Quick Parts',
    ],
    prerequisites: ['Basic computer literacy (opening, saving and editing a file)'],
    targetAudience: ['Office assistants and executives', 'Students writing reports and project documents', 'Anyone preparing for office/clerical roles'],
    tags: ['office', 'word', 'documents', 'typing', 'productivity'],
    certificateAvailable: true,
    featured: false,
  },
  {
    id: 'MSExcel',
    slug: 'ms-excel',
    title: 'MS Excel — Data, Formulas & Office Reporting',
    shortTitle: 'MS Excel',
    description:
      'Excel the Excel way: build tables, formulas, lookups (VLOOKUP/XLOOKUP), pivot tables, charts, data validation and conditional formatting to turn raw data into office-ready reports.',
    shortDescription: 'Formulas, lookups, pivot tables, charts and reports for daily office data work.',
    categorySlug: 'computer-office',
    price: 599,
    difficulty: 'Beginner',
    duration: '5 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Design clean, correct spreadsheets with named ranges and data validation',
      'Write formulas and functions: SUMIFS, COUNTIFS, IF, and nested logic',
      'Look up data with VLOOKUP, XLOOKUP and INDEX-MATCH',
      'Summarize large data with pivot tables and pivot charts',
      'Print and present reports that look professional and stay accurate',
    ],
    prerequisites: ['Basic computer literacy and simple arithmetic'],
    targetAudience: ['Office assistants, accountants and data entry staff', 'Small-business owners tracking sales and stock', 'Students building their first data reports'],
    tags: ['excel', 'spreadsheet', 'formulas', 'pivot', 'data'],
    certificateAvailable: true,
    featured: true,
  },
  {
    id: 'MSPowerPoint',
    slug: 'ms-powerpoint',
    title: 'MS PowerPoint — Impactful Presentations',
    shortTitle: 'MS PowerPoint',
    description:
      'Design presentations that people actually remember: master slides, layouts, SmartArt, charts, animations, speaker notes and delivery techniques for meetings, pitches and training sessions.',
    shortDescription: 'Master slides, layouts, visuals and delivery for meeting-ready presentations.',
    categorySlug: 'computer-office',
    price: 499,
    difficulty: 'Beginner',
    duration: '3 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Build a consistent deck fast using master slides and layouts',
      'Visualize ideas with SmartArt, charts, icons and tables',
      'Animate purposefully — not as decoration',
      'Use speaker notes, rehearse and deliver a confident presentation',
      'Export and share in PDF, video and broadcast formats',
    ],
    prerequisites: ['Basic computer literacy'],
    targetAudience: ['Students presenting seminars', 'Sales and training professionals', 'Anyone pitching ideas to a group'],
    tags: ['powerpoint', 'presentation', 'slides', 'design'],
    certificateAvailable: true,
    featured: false,
  },
  {
    id: 'ComputerFundamentals',
    slug: 'computer-fundamentals',
    title: 'Computer Fundamentals — Start from Zero',
    shortTitle: 'Computer Fundamentals',
    description:
      'A gentle, complete beginner course: how computers and the internet work, Windows file management, typing, email, safety, and the productivity basics you need before any office or technical job.',
    shortDescription: 'How computers and the internet work, files, email, typing and online safety.',
    categorySlug: 'computer-office',
    price: 399,
    difficulty: 'Beginner',
    duration: '4 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Explain the main parts of a computer and how they work together',
      'Manage files and folders confidently in Windows',
      'Use email, the web and search engines safely and productively',
      'Practice touch typing and common shortcuts',
      'Protect yourself from scams, malware and identity theft online',
    ],
    prerequisites: ['No prior knowledge — this course assumes zero computer experience'],
    targetAudience: ['First-time computer users', 'Students starting their IT journey', 'Job seekers preparing for basic computer tests'],
    tags: ['computer', 'basics', 'windows', 'internet', 'safety'],
    certificateAvailable: true,
    featured: false,
  },

  // ── Programming ─────────────────────────────────────────────────────────
  {
    id: 'Java',
    slug: 'java',
    title: 'Java Programming from Scratch',
    shortTitle: 'Java',
    description:
      'Learn Java the practical way: syntax, classes and objects, collections, exception handling, file I/O and a real console project — with compilable examples at every step.',
    shortDescription: 'Core Java: OOP, collections, exceptions, files and a hands-on project.',
    categorySlug: 'programming',
    price: 699,
    difficulty: 'Beginner',
    duration: '6 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Write, compile and run Java programs with JDK and any editor',
      'Understand variables, control flow, arrays and methods',
      'Model real things with classes, objects, inheritance and interfaces',
      'Use collections, generics and lambda expressions',
      'Handle errors with exceptions and read/write files safely',
    ],
    prerequisites: ['Basic computer literacy; no programming experience required'],
    targetAudience: ['Students learning their first serious language', 'Android and backend aspirants', 'Anyone adding Java to their skill set'],
    tags: ['java', 'programming', 'oop', 'jvm'],
    certificateAvailable: true,
    featured: true,
  },
  {
    id: 'JavaScript',
    slug: 'javascript',
    title: 'JavaScript — The Language of the Web',
    shortTitle: 'JavaScript',
    description:
      'Modern JavaScript from first principles: values, functions, arrays, objects, DOM manipulation, events, async/await and fetch — enough to make any web page interactive.',
    shortDescription: 'Modern JS: syntax, functions, the DOM, events, async and fetch.',
    categorySlug: 'programming',
    price: 699,
    difficulty: 'Beginner',
    duration: '6 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Write modern ES6+ JavaScript with let/const, arrow functions and template strings',
      'Manipulate the DOM and respond to user events',
      'Work with arrays, objects, destructuring and spread',
      'Use promises and async/await to call web APIs with fetch',
      'Debug effectively with the browser developer console',
    ],
    prerequisites: ['Basic HTML understanding is helpful but not required'],
    targetAudience: ['Web development starters', 'Frontend career aspirants', 'Anyone automating the browser with scripts'],
    tags: ['javascript', 'web', 'es6', 'dom', 'async'],
    certificateAvailable: true,
    featured: false,
  },
  {
    id: 'DSA',
    slug: 'dsa',
    title: 'Data Structures & Algorithms in Java',
    shortTitle: 'DSA',
    description:
      'The DSA foundations behind interview questions: arrays, linked lists, stacks, queues, trees, graphs, sorting, searching, recursion, hashing and Big-O — with Java implementations and practice problems.',
    shortDescription: 'Arrays to graphs: complexity, recursion, sorting, hashing and trees in Java.',
    categorySlug: 'programming',
    price: 799,
    difficulty: 'Intermediate',
    duration: '8 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Analyze algorithms with Big-O time and space complexity',
      'Implement and use arrays, linked lists, stacks, queues and deques',
      'Solve problems with recursion, backtracking and hashing',
      'Master binary search trees, heaps and basic graph traversals',
      'Choose the right data structure and sorting strategy for a problem',
    ],
    prerequisites: ['Comfortable with basic Java or any programming language'],
    targetAudience: ['Students preparing for technical interviews', 'CS/IT undergraduates', 'Programmers sharpening problem-solving skills'],
    tags: ['dsa', 'algorithms', 'interview', 'data-structures'],
    certificateAvailable: true,
    featured: true,
  },

  // ── Web Development ─────────────────────────────────────────────────────
  {
    id: 'HTMLCSS',
    slug: 'html-css',
    title: 'HTML & CSS — Build Your First Websites',
    shortTitle: 'HTML & CSS',
    description:
      'Build real, responsive web pages from scratch: semantic HTML, CSS selectors, the box model, Flexbox, Grid, responsive design and a complete landing-page project.',
    shortDescription: 'Semantic HTML, Flexbox, Grid and responsive layouts for real pages.',
    categorySlug: 'web-development',
    price: 499,
    difficulty: 'Beginner',
    duration: '4 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Structure pages with semantic HTML5 tags',
      'Style with CSS: selectors, colors, typography, spacing and the box model',
      'Create responsive layouts with Flexbox and Grid',
      'Build forms that are usable and accessible',
      'Ship a complete, responsive landing page project',
    ],
    prerequisites: ['Basic computer literacy; no coding experience required'],
    targetAudience: ['Web design starters', 'Students building their first portfolio', 'Anyone who wants to understand how pages work'],
    tags: ['html', 'css', 'web', 'responsive', 'frontend'],
    certificateAvailable: true,
    featured: false,
  },
  {
    id: 'React',
    slug: 'react',
    title: 'React — Build Modern Interfaces',
    shortTitle: 'React',
    description:
      'Component thinking with React: JSX, props, state, hooks, forms, routing, fetching data and deploying a real single-page app.',
    shortDescription: 'Components, props, state, hooks, routing and data fetching with React.',
    categorySlug: 'web-development',
    price: 699,
    difficulty: 'Intermediate',
    duration: '6 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Break a UI into reusable components',
      'Manage state with useState, useEffect and custom hooks',
      'Fetch and display data from an API with loading/error states',
      'Implement client-side routing with React Router',
      'Build and deploy a complete React application',
    ],
    prerequisites: ['Working knowledge of HTML, CSS and JavaScript'],
    targetAudience: ['Frontend developers leveling up', 'JavaScript developers going professional', 'Students building portfolio apps'],
    tags: ['react', 'hooks', 'components', 'spa', 'frontend'],
    certificateAvailable: true,
    featured: false,
  },
  {
    id: 'NodeJS',
    slug: 'node-js',
    title: 'Node.js — Backend APIs with JavaScript',
    shortTitle: 'Node.js',
    description:
      'Run JavaScript on the server: the event loop, npm, Express, REST APIs, middleware, working with files, databases and a deployable backend project.',
    shortDescription: 'npm, Express, REST APIs, middleware and databases with Node.js.',
    categorySlug: 'web-development',
    price: 699,
    difficulty: 'Intermediate',
    duration: '6 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Understand the Node.js event loop and module system',
      'Build REST APIs with Express: routes, params, bodies and errors',
      'Use middleware for logging, parsing and authentication',
      'Store data with a database and an ORM',
      'Handle async work correctly with async/await',
    ],
    prerequisites: ['Comfortable with JavaScript basics'],
    targetAudience: ['JavaScript developers going backend', 'Students building full-stack projects', 'API and microservice beginners'],
    tags: ['nodejs', 'express', 'api', 'backend', 'javascript'],
    certificateAvailable: true,
    featured: false,
  },
  {
    id: 'FullStackWeb',
    slug: 'full-stack-web',
    title: 'Full Stack Web Development — MERN Projects',
    shortTitle: 'Full Stack Web',
    description:
      'The complete path: frontend (React) + backend (Node/Express) + database (MongoDB) + auth, and two deployable projects that combine everything into one product.',
    shortDescription: 'React + Node/Express + MongoDB: build and deploy two complete apps.',
    categorySlug: 'web-development',
    price: 999,
    difficulty: 'Intermediate',
    duration: '12 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Build a React frontend connected to a real API',
      'Design and build REST APIs with Node.js and Express',
      'Model and query data with MongoDB and Mongoose',
      'Implement JWT authentication end-to-end',
      'Deploy a full-stack application to a live host',
    ],
    prerequisites: ['Working knowledge of HTML, CSS, JavaScript and basics of React/Node'],
    targetAudience: ['Developers who know one side and want the full stack', 'Freelancers and career changers building complete products', 'Students doing final-year projects'],
    tags: ['mern', 'fullstack', 'react', 'nodejs', 'mongodb'],
    certificateAvailable: true,
    featured: true,
  },

  // ── Systems & Technology ────────────────────────────────────────────────
  {
    id: 'Linux',
    slug: 'linux',
    title: 'Linux Essentials — Terminal to Administration',
    shortTitle: 'Linux',
    description:
      'From first login to daily administration: the filesystem, essential commands, pipes and redirection, users and permissions, processes, package managers, shell scripts and the basics of servers.',
    shortDescription: 'Filesystem, commands, permissions, processes and shell scripting on Linux.',
    categorySlug: 'systems-technology',
    price: 599,
    difficulty: 'Beginner',
    duration: '5 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Navigate and manage the Linux filesystem from the terminal',
      'Chain commands with pipes, redirection and grep',
      'Manage users, groups and file permissions',
      'Monitor processes, services and system resources',
      'Write simple Bash scripts to automate tasks',
    ],
    prerequisites: ['Basic computer literacy; no Linux experience required'],
    targetAudience: ['Students entering IT operations', 'Developers deploying to Linux servers', 'Anyone switching to Linux'],
    tags: ['linux', 'bash', 'terminal', 'sysadmin'],
    certificateAvailable: true,
    featured: false,
  },
  {
    id: 'Networking',
    slug: 'networking',
    title: 'Networking Fundamentals — How Networks Work',
    shortTitle: 'Networking',
    description:
      'Understand the network under every device: OSI and TCP/IP models, IP addressing and subnetting, DNS, DHCP, routing and switching, Wi-Fi, and the tools used to diagnose real network faults.',
    shortDescription: 'TCP/IP, IP addressing, DNS, DHCP, routing, switching and diagnostics.',
    categorySlug: 'systems-technology',
    price: 699,
    difficulty: 'Beginner',
    duration: '5 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Explain the OSI and TCP/IP models with real protocols',
      'Plan IP addressing and subnetting for small networks',
      'Understand how DNS and DHCP work in practice',
      'Describe routing, switching, VLANs and Wi-Fi basics',
      'Diagnose connectivity problems with ping, traceroute and ip',
    ],
    prerequisites: ['Basic computer usage; no networking background required'],
    targetAudience: ['IT support and help-desk starters', 'Students preparing for CCNA-style fundamentals', 'Home network troubleshooters'],
    tags: ['networking', 'tcpip', 'ip', 'dns', 'ccna'],
    certificateAvailable: true,
    featured: false,
  },

  // ── IoT ─────────────────────────────────────────────────────────────────
  {
    id: 'Arduino',
    slug: 'arduino',
    title: 'Arduino — Hands-On Electronics & Coding',
    shortTitle: 'Arduino',
    description:
      'Build real hardware projects: the Arduino IDE, digital and analog I/O, sensors, actuators, serial communication, PWM, interrupts and a complete home-automation style project.',
    shortDescription: 'I/O, sensors, actuators, serial and PWM — build real Arduino projects.',
    categorySlug: 'iot',
    price: 599,
    difficulty: 'Beginner',
    duration: '5 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Wire and program LEDs, buttons, sensors and motors on Arduino',
      'Read analog and digital inputs and control PWM outputs',
      'Communicate with a PC using serial and with devices using I2C/SPI',
      'Debounce inputs and write clean, structured sketches',
      'Design and build a complete sensor-based project',
    ],
    prerequisites: ['Basic computer literacy; coding experience is a plus but not required'],
    targetAudience: ['Hobbyists and makers', 'ECE/EEE students', 'IoT career starters'],
    tags: ['arduino', 'embedded', 'sensors', 'iot', 'electronics'],
    certificateAvailable: true,
    featured: true,
  },
  {
    id: 'ESP32',
    slug: 'esp32',
    title: 'ESP32 — Wi-Fi & Bluetooth IoT Projects',
    shortTitle: 'ESP32',
    description:
      'The connected microcontroller: ESP32 architecture, Arduino core, Wi-Fi and HTTP clients, Bluetooth, deep sleep, OTA updates and a cloud-connected IoT project.',
    shortDescription: 'ESP32 Wi-Fi, HTTP, Bluetooth, deep sleep and cloud-connected IoT.',
    categorySlug: 'iot',
    price: 699,
    difficulty: 'Intermediate',
    duration: '6 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Program ESP32 boards with the Arduino core and PlatformIO',
      'Connect to Wi-Fi and make HTTP requests from the device',
      'Use Bluetooth/BLE to bridge sensors to phones',
      'Reduce power with deep sleep and wake sources',
      'Push sensor data to a cloud dashboard in a complete project',
    ],
    prerequisites: ['Basic Arduino or microcontroller experience'],
    targetAudience: ['IoT developers and makers', 'ECE/EEE students', 'Product prototypes with real connectivity'],
    tags: ['esp32', 'wifi', 'ble', 'iot', 'embedded'],
    certificateAvailable: true,
    featured: false,
  },

  // ── Embedded Systems ────────────────────────────────────────────────────
  {
    id: 'EmbeddedC',
    slug: 'embedded-c',
    title: 'Embedded C — Firmware for Microcontrollers',
    shortTitle: 'Embedded C',
    description:
      'C for the hardware: registers and bit manipulation, timers, GPIO, interrupts, serial protocols (UART/SPI/I2C), and writing clean, low-level firmware for microcontrollers.',
    shortDescription: 'Registers, GPIO, interrupts, timers and protocols in C for MCUs.',
    categorySlug: 'embedded-systems',
    price: 699,
    difficulty: 'Intermediate',
    duration: '6 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Manipulate registers and bits safely in C',
      'Configure GPIO, timers and interrupts on a microcontroller',
      'Communicate with UART, SPI and I2C peripherals',
      'Write structured firmware with no RTOS dependencies',
      'Debug hardware with oscilloscopes and logic analyzers',
    ],
    prerequisites: ['Working knowledge of C basics'],
    targetAudience: ['ECE/EEE students and graduates', 'Embedded developers moving into firmware', 'IoT and robotics makers'],
    tags: ['embedded-c', 'firmware', 'mcu', 'c', 'registers'],
    certificateAvailable: true,
    featured: false,
  },
  {
    id: 'Microcontrollers',
    slug: 'microcontrollers',
    title: 'Microcontrollers — Architecture & Interfacing',
    shortTitle: 'Microcontrollers',
    description:
      'The heart of every smart device: MCU architecture, memory maps, clocks, the 8051 and ARM Cortex basics, peripherals, interfacing LEDs, displays, keypads, ADCs and motors.',
    shortDescription: 'MCU architecture, clocks, peripherals and interfacing LEDs, displays and sensors.',
    categorySlug: 'embedded-systems',
    price: 699,
    difficulty: 'Intermediate',
    duration: '6 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Read a microcontroller datasheet and memory map',
      'Explain clocking, reset and power domains',
      'Interface LEDs, 7-segment displays, LCDs and keypads',
      'Use ADC, timers and PWM for sensors and motors',
      'Compare 8051, AVR, PIC and ARM Cortex MCUs for a task',
    ],
    prerequisites: ['Basic electronics and C programming knowledge'],
    targetAudience: ['ECE/EEE students', 'Embedded engineers refreshing fundamentals', 'Makers going beyond Arduino'],
    tags: ['microcontroller', '8051', 'arm', 'peripherals', 'interfacing'],
    certificateAvailable: true,
    featured: false,
  },

  // ── Electronics ─────────────────────────────────────────────────────────
  {
    id: 'BasicElectronics',
    slug: 'basic-electronics',
    title: 'Basic Electronics — Voltage to Circuits',
    shortTitle: 'Basic Electronics',
    description:
      'From zero to working circuits: voltage, current, resistance, Ohm’s law, series/parallel circuits, capacitors, diodes, transistors, soldering basics and reading schematics.',
    shortDescription: 'Voltage, current, resistors, capacitors, diodes and your first circuits.',
    categorySlug: 'electronics',
    price: 499,
    difficulty: 'Beginner',
    duration: '5 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Explain voltage, current, resistance and power with Ohm’s law',
      'Analyze series and parallel resistor networks',
      'Understand how capacitors, diodes and transistors behave',
      'Read schematics and identify common components',
      'Solder and test simple circuits safely',
    ],
    prerequisites: ['Basic arithmetic; no electronics background required'],
    targetAudience: ['Diploma and degree students', 'Makers and hobbyists', 'Anyone starting electronics repair'],
    tags: ['electronics', 'ohm', 'circuit', 'components', 'basics'],
    certificateAvailable: true,
    featured: false,
  },
  {
    id: 'DigitalElectronics',
    slug: 'digital-electronics',
    title: 'Digital Electronics — Logic to Digital Systems',
    shortTitle: 'Digital Electronics',
    description:
      'How 0s and 1s build computers: number systems, logic gates, Boolean algebra, combinational circuits (multiplexers, decoders, adders) and sequential circuits (flip-flops, counters, registers).',
    shortDescription: 'Number systems, logic gates, Boolean algebra, flip-flops and counters.',
    categorySlug: 'electronics',
    price: 599,
    difficulty: 'Intermediate',
    duration: '5 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Convert between binary, octal, hex and decimal',
      'Simplify logic with Boolean algebra and Karnaugh maps',
      'Design combinational circuits: adders, multiplexers and decoders',
      'Design sequential circuits with flip-flops, counters and registers',
      'Understand the basics of state machines',
    ],
    prerequisites: ['Basic electronics or high-school physics'],
    targetAudience: ['ECE/EEE and CS students', 'Digital design and VLSI aspirants', 'Hardware enthusiasts'],
    tags: ['digital', 'logic-gates', 'boolean', 'flip-flop', 'counters'],
    certificateAvailable: true,
    featured: false,
  },
  {
    id: 'PCBDesign',
    slug: 'pcb-design',
    title: 'PCB Design — Schematic to Manufactured Board',
    shortTitle: 'PCB Design',
    description:
      'Design professional printed circuit boards: schematics, component footprints, layout and routing rules, grounding, thermal management, design for manufacturing and ordering your first board.',
    shortDescription: 'Schematic, footprint, layout, routing and DFM for real boards.',
    categorySlug: 'electronics',
    price: 699,
    difficulty: 'Intermediate',
    duration: '6 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Design a clean schematic with a schematic editor (KiCad)',
      'Create and verify component footprints',
      'Route a two-layer PCB following design rules',
      'Apply grounding, decoupling and thermal design practices',
      'Generate Gerbers and order a manufacturable board',
    ],
    prerequisites: ['Basic electronics knowledge'],
    targetAudience: ['Electronics designers and students', 'Makers turning circuits into products', 'IoT hardware developers'],
    tags: ['pcb', 'kicad', 'layout', 'gerber', 'electronics'],
    certificateAvailable: true,
    featured: false,
  },

  // ── CAD & Design ────────────────────────────────────────────────────────
  {
    id: 'AutoCAD2D',
    slug: 'autocad-2d',
    title: 'AutoCAD 2D — Technical Drafting',
    shortTitle: 'AutoCAD 2D',
    description:
      'Produce accurate 2D technical drawings: the AutoCAD interface, drawing and modify commands, layers, text and dimensions, blocks, plotting to scale and a real mechanical drawing project.',
    shortDescription: 'Drawing commands, layers, dimensions, blocks and plotted 2D drawings.',
    categorySlug: 'cad-design',
    price: 599,
    difficulty: 'Beginner',
    duration: '5 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Navigate the AutoCAD interface and use precision drafting tools',
      'Draw and modify geometry with lines, polylines, fillets and arrays',
      'Organize drawings with layers and manage object properties',
      'Add text, dimensions and hatching to industry conventions',
      'Plot and print scaled drawings to correct sheet layouts',
    ],
    prerequisites: ['Basic computer literacy; mechanical drawing sense is helpful'],
    targetAudience: ['Mechanical and civil diploma students', 'Drafters and junior design engineers', 'CAD job aspirants'],
    tags: ['autocad', 'cad', '2d', 'drafting', 'mechanical'],
    certificateAvailable: true,
    featured: false,
  },
  {
    id: 'ThreeDCAD',
    slug: '3d-cad',
    title: '3D CAD — Parametric Solid Modeling',
    shortTitle: '3D CAD',
    description:
      'Design in three dimensions: sketching and constraints, extrusions and revolves, features and boolean operations, assemblies, assemblies and drawings, plus 3D printing preparation.',
    shortDescription: 'Parametric sketches, solid models, assemblies and 3D-print-ready parts.',
    categorySlug: 'cad-design',
    price: 799,
    difficulty: 'Intermediate',
    duration: '6 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Sketch with constraints and dimensions that drive the model',
      'Build solid models with extrusions, revolves, sweeps and lofts',
      'Create features: fillets, chamfers, holes, patterns and shells',
      'Assemble parts with mates and produce exploded views',
      'Export models for 3D printing and engineering drawings',
    ],
    prerequisites: ['Basic CAD or drafting knowledge'],
    targetAudience: ['Mechanical design students', 'Product designers and makers', 'Engineers learning parametric modeling'],
    tags: ['cad', '3d', 'solid-modeling', 'parametric', 'fusion'],
    certificateAvailable: true,
    featured: false,
  },

  // ── ITI & Trade Training ────────────────────────────────────────────────
  {
    id: 'ITICOPA',
    slug: 'iti-copa',
    title: 'ITI COPA — Computer Operator & Programming Assistant',
    shortTitle: 'ITI COPA',
    description:
      'Job-ready office computer skills for COPA trade: typing, operating systems, MS Office, internet, basic computer hardware maintenance, data entry and simple programming awareness.',
    shortDescription: 'Office computing, data entry, hardware basics and typing for COPA trade.',
    categorySlug: 'iti-trade-training',
    price: 799,
    difficulty: 'Beginner',
    duration: '6 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Type accurately and use Windows and office applications fluently',
      'Enter and manage data with spreadsheets and databases',
      'Provide basic computer hardware and printer maintenance',
      'Use the internet for email, forms and official work',
      'Understand the basics of programming and scripting',
    ],
    prerequisites: ['10th pass or equivalent; no prior computer training needed'],
    targetAudience: ['ITI COPA trainees supplementing their trade', 'Office assistant and data entry job seekers'],
    tags: ['iti', 'copa', 'office', 'computer', 'data-entry'],
    certificateAvailable: true,
    featured: false,
  },
  {
    id: 'ITIElectrician',
    slug: 'iti-electrician',
    title: 'ITI Electrician — Wiring, Machines & Safety',
    shortTitle: 'ITI Electrician',
    description:
      'Practical electrical trade fundamentals: safety and first aid, wiring systems, house wiring, electrical machines, measurement instruments, motors, transformers and troubleshooting — with strict safety practice.',
    shortDescription: 'House wiring, electrical machines, instruments and safe troubleshooting.',
    categorySlug: 'iti-trade-training',
    price: 899,
    difficulty: 'Beginner',
    duration: '8 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Apply electrical safety rules and first aid for electric shock',
      'Read wiring diagrams and install house wiring circuits',
      'Understand electrical machines: motors, transformers and generators',
      'Use measurement instruments: multimeter, clamp meter, megger',
      'Troubleshoot common faults safely and systematically',
    ],
    prerequisites: ['10th pass or equivalent; basic science understanding'],
    targetAudience: ['ITI Electrician trainees', 'Apprentice electricians and helpers', 'Home-wiring DIY learners with care'],
    tags: ['iti', 'electrician', 'wiring', 'safety', 'machines'],
    certificateAvailable: true,
    featured: false,
  },
  {
    id: 'ITIFitter',
    slug: 'iti-fitter',
    title: 'ITI Fitter — Workshop Measurement & Fitting',
    shortTitle: 'ITI Fitter',
    description:
      'The fitter trade in practice: workshop safety, measuring instruments, marking, filing, drilling, threading, fitting of keys and pins, and reading engineering drawings for mechanical assembly work.',
    shortDescription: 'Measurement, marking, filing, drilling, threading and drawing reading.',
    categorySlug: 'iti-trade-training',
    price: 899,
    difficulty: 'Beginner',
    duration: '8 weeks',
    language: 'English (Hinglish support)',
    learningOutcomes: [
      'Work safely in a workshop and maintain hand tools',
      'Measure accurately with vernier calipers, micrometers and gauges',
      'Mark out workpieces with scribers, punches and squares',
      'Perform filing, sawing, drilling, reaming and threading',
      'Read engineering drawings and assemble simple mechanisms',
    ],
    prerequisites: ['10th pass or equivalent; willingness to do hands-on work'],
    targetAudience: ['ITI Fitter trainees', 'Machine-shop apprentices', 'Mechanical maintenance job seekers'],
    tags: ['iti', 'fitter', 'workshop', 'measurement', 'mechanical'],
    certificateAvailable: true,
    featured: false,
  },
];

export const COURSE_BY_ID: Record<string, NewCourseMeta> = Object.fromEntries(
  NEW_COURSES.map((c) => [c.id, c])
);
